Repository kgu-moneyplanet/moneyplanet-BE, pull requests merged in 2025-05, with the labels that each got.

#26 Feat: Weekly, Monthly 통계 TBL 및 기능 구현 (23)
  app/src/main/java/com/money/app/stat/monthlystat/controller/MonthlyStatController.java
  app/src/main/java/com/money/app/stat/monthlystat/domain/MonthlyStat.java
  app/src/main/java/com/money/app/stat/monthlystat/dto/MonthlySumStatListResponseDto.java
  app/src/main/java/com/money/app/stat/monthlystat/dto/MonthlySummaryStatDto.java
  app/src/main/java/com/money/app/stat/monthlystat/repository/MonthlyStatRepository.java
  app/src/main/java/com/money/app/stat/monthlystat/service/MonthlyStatService.java
  app/src/main/java/com/money/app/stat/weeklystat/controller/WeeklyStatController.java
  app/src/main/java/com/money/app/stat/weeklystat/domain/WeeklyStat.java
  app/src/main/java/com/money/app/stat/weeklystat/dto/WeeklyLWTWAmountDto.java
  app/src/main/java/com/money/app/stat/weeklystat/dto/WeeklySumStatListResponseDto.java
  app/src/main/java/com/money/app/stat/weeklystat/dto/WeeklySummaryStatDto.java
  app/src/main/java/com/money/app/stat/weeklystat/repository/WeeklyStatRepository.java
  app/src/main/java/com/money/app/stat/weeklystat/service/WeeklyStatService.java
Labels: Feature

#28 Feature/user logout#12
  app/src/main/java/com/money/app/security/JwtService.java
  app/src/main/java/com/money/app/user/controller/AuthController.java
  app/src/main/java/com/money/app/user/controller/UserController.java
  app/src/main/java/com/money/app/user/service/AuthService.java
  app/src/main/java/com/money/app/user/service/UserDetailsServiceImpl.java
  app/src/main/java/com/money/app/user/service/UserService.java
  app/src/main/java/com/money/app/util/exception/ErrorCode.java
Labels: Bug, Feature

#30 Fix: BlacklistToken 관련 수정(29)
  app/src/main/java/com/money/app/security/BlacklistToken.java
  app/src/main/java/com/money/app/security/BlacklistTokenRepository.java
Labels: Bug

#34 Chore: Docker 환경세팅 (#19)
  app/Dockerfile
  app/src/main/java/com/money/app/AppApplication.java
  app/src/main/java/com/money/app/config/SecurityConfig.java
  app/src/main/resources/application.yml
  docker-compose.yml
Labels: Setting, Deploy

#36 Feat: Category Data 자동 입력기능 구현 (#35)
  app/src/main/java/com/money/app/config/InitializerConfig.java
  app/src/main/java/com/money/app/module/category/service/CategoryService.java
Labels: Feature

#37 [Feat] User target(도달율) 계산 기능 구현 #24
  app/src/main/java/com/money/app/module/tx/repository/TxRepository.java
  app/src/main/java/com/money/app/module/user/controller/UserController.java
  app/src/main/java/com/money/app/module/user/domain/User.java
  app/src/main/java/com/money/app/module/user/dto/UserDto.java
  app/src/main/java/com/money/app/module/user/dto/UserResponseDto.java
  app/src/main/java/com/money/app/module/user/service/UserTargetCalculationService.java
Labels: Feature

#39 Chore: 서버 배포를 위한 CORS 설정 (#38)
  app/src/main/java/com/money/app/config/WebConfig.java
  app/src/main/java/com/money/app/module/category/service/CategoryService.java
  app/src/main/java/com/money/app/util/exception/Handler.java
Labels: Feature, Deploy

#43 Fix: user create, update api 수정(#42)
  app/src/main/java/com/money/app/module/tx/dto/InputSchema.java
  app/src/main/java/com/money/app/module/user/domain/User.java
  app/src/main/java/com/money/app/module/user/dto/UserCreateDto.java
  app/src/main/java/com/money/app/module/user/dto/UserDto.java
  app/src/main/java/com/money/app/module/user/dto/UserResponseDto.java
  app/src/main/java/com/money/app/module/user/dto/UserUpdateDto.java
  app/src/main/java/com/money/app/module/user/service/UserService.java
  app/src/main/java/com/money/app/util/common/enumtype/PlanetType.java
Labels: Bug, Feature

#45 Refact: AI Report 관련 reason - feedback 통합 (#44)
  app/src/main/java/com/money/app/module/tx/dto/DecisionResponseDto.java
  app/src/main/java/com/money/app/module/tx/dto/ReportUpdateDto.java
  app/src/main/java/com/money/app/module/tx/dto/TxCreateDto.java
  app/src/main/java/com/money/app/module/tx/service/TxService.java
Labels: Refactoring

#46 Feat: ABC API 구현 (#27)
  app/build.gradle
  app/src/main/java/com/money/app/config/FastApiRestTemplateConfig.java
  app/src/main/java/com/money/app/external/FastApiConnect.java
  app/src/main/java/com/money/app/module/tx/dto/DecisionResponseDto.java
  app/src/main/java/com/money/app/module/tx/dto/InputSchema.java
  app/src/main/java/com/money/app/module/tx/service/TxService.java
  docker-compose.yml
Labels: Feature

#50 Fix: TX 저장시 Report 저장 실패 (#49)
  app/src/main/java/com/money/app/module/tx/domain/Report.java
Labels: Bug
